name: Update Terraform Common Submodule

on:
  schedule:
    - cron: '0 0 * * *' # Run once a day
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  update_submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: ${{ github.ref }}
      - name: Check for submodule changes
        id: check_changes
        run: |
          # Check for changes in submodules
          if ! git submodule update --remote --recursive --quiet; then
            echo "updated=true" >> $GITHUB_OUTPUT
            # Create a new branch for updating the submodule
            cd submodule-directory && git checkout -b submodule-update
            # Push the branch to the remote
            git push origin submodule-update
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
      - name: Create PR
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'update tf-modules submodule'
          title: 'Update `tf-modules` submodule'
          body: 'This PR updates the `tf-modules` submodule to its latest versions.'
          branch: 'submodule-update-tf-modules'
          labels: 'submodule-update'
          delete-branch: true
